server {
    listen 80;
    server_name localhost;

    location /radar/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /radar/index.html;
    }

    # Proxy API requests to the backend
    location /api/ {
        proxy_pass http://backend:3001/api/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }

    # Proxy storage requests to the backend
    location /radar/order_attachments/ {
        proxy_pass http://backend:3001/order_attachments/;
    }

    location /radar/payment_receipts/ {
        proxy_pass http://backend:3001/payment_receipts/;
    }

    location /radar/delivery_proofs/ {
        proxy_pass http://backend:3001/delivery_proofs/;
    }

    # Fallback to redirect root to /radar/
    location = / {
        return 301 /radar/;
    }
}
